/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as DemoMcpTodosRouteImport } from './routes/demo.mcp-todos'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardInvestmentsRouteImport } from './routes/dashboard/investments'
import { Route as OnboardingRegisterRouteImport } from './routes/_onboarding/register'
import { Route as OnboardingForgotPasswordRouteImport } from './routes/_onboarding/forgot-password'
import { Route as AuthVerifyOtpRouteImport } from './routes/_auth/verify-otp'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/_public/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoMcpTodosRoute = DemoMcpTodosRouteImport.update({
  id: '/demo/mcp-todos',
  path: '/demo/mcp-todos',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardInvestmentsRoute = DashboardInvestmentsRouteImport.update({
  id: '/investments',
  path: '/investments',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const OnboardingRegisterRoute = OnboardingRegisterRouteImport.update({
  id: '/_onboarding/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingForgotPasswordRoute =
  OnboardingForgotPasswordRouteImport.update({
    id: '/_onboarding/forgot-password',
    path: '/forgot-password',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthVerifyOtpRoute = AuthVerifyOtpRouteImport.update({
  id: '/_auth/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/forgot-password': typeof OnboardingForgotPasswordRoute
  '/register': typeof OnboardingRegisterRoute
  '/dashboard/investments': typeof DashboardInvestmentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof AuthLoginRoute
  '/verify-otp': typeof AuthVerifyOtpRoute
  '/forgot-password': typeof OnboardingForgotPasswordRoute
  '/register': typeof OnboardingRegisterRoute
  '/dashboard/investments': typeof DashboardInvestmentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/verify-otp': typeof AuthVerifyOtpRoute
  '/_onboarding/forgot-password': typeof OnboardingForgotPasswordRoute
  '/_onboarding/register': typeof OnboardingRegisterRoute
  '/dashboard/investments': typeof DashboardInvestmentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/demo/mcp-todos': typeof DemoMcpTodosRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/login'
    | '/verify-otp'
    | '/forgot-password'
    | '/register'
    | '/dashboard/investments'
    | '/dashboard/profile'
    | '/demo/mcp-todos'
    | '/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/verify-otp'
    | '/forgot-password'
    | '/register'
    | '/dashboard/investments'
    | '/dashboard/profile'
    | '/demo/mcp-todos'
    | '/'
    | '/dashboard'
  id:
    | '__root__'
    | '/dashboard'
    | '/_auth/login'
    | '/_auth/verify-otp'
    | '/_onboarding/forgot-password'
    | '/_onboarding/register'
    | '/dashboard/investments'
    | '/dashboard/profile'
    | '/demo/mcp-todos'
    | '/_public/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthVerifyOtpRoute: typeof AuthVerifyOtpRoute
  OnboardingForgotPasswordRoute: typeof OnboardingForgotPasswordRoute
  OnboardingRegisterRoute: typeof OnboardingRegisterRoute
  DemoMcpTodosRoute: typeof DemoMcpTodosRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/mcp-todos': {
      id: '/demo/mcp-todos'
      path: '/demo/mcp-todos'
      fullPath: '/demo/mcp-todos'
      preLoaderRoute: typeof DemoMcpTodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/investments': {
      id: '/dashboard/investments'
      path: '/investments'
      fullPath: '/dashboard/investments'
      preLoaderRoute: typeof DashboardInvestmentsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/_onboarding/register': {
      id: '/_onboarding/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof OnboardingRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/forgot-password': {
      id: '/_onboarding/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof OnboardingForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-otp': {
      id: '/_auth/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof AuthVerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardInvestmentsRoute: typeof DashboardInvestmentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardInvestmentsRoute: DashboardInvestmentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthVerifyOtpRoute: AuthVerifyOtpRoute,
  OnboardingForgotPasswordRoute: OnboardingForgotPasswordRoute,
  OnboardingRegisterRoute: OnboardingRegisterRoute,
  DemoMcpTodosRoute: DemoMcpTodosRoute,
  PublicIndexRoute: PublicIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.tsx'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
